language: python

python:
  - 3.5
  - 3.6

install: pip install .

script: python setup.py test

jobs:
  include:
    - stage: format
      name: "Check format"
      python: 3.6
      install: pip install autopep8
      script:
        - python setup.py check_format --directory docs --file-type python
        - python setup.py check_format --directory hep_rfm --file-type python
        - python setup.py check_format --directory scripts --file-type all
        - python setup.py check_format --directory tests --file-type python
